export const ROLE_KEY = 'role';
export const roles = [
  {
    id: '79ac524c-6d0f-4c71-a332-3bec6409ee68',
    libelle: 'manager',
    rules: [
      'dashboard_sup:view',
      'dashboard_ops:view',
      'dashboard_fin:view',
      'dashboard_acc:view',
      'dashboard_admin:view',

      'unloading:list',
      'unloading:more',
      'storage:list',
      'storage:more',
      'packing_plan:list',
      'packing_plan:more',
      'packing_execution:list',
      'packing_execution:more',
      'booking:list',
      'booking:more',
      'container:list',
      'container:more',
      'bill_of_lading:list',
      'bill_of_lading:more',
      'inventory:view',
      'exporter_report:view',
      'general_report:view',

      'accounts:list',
      'accounts:more',
      'supplier_prefinancing:list',
      'supplier_prefinancing:more',
      'pledge_request:list',
      'pledge_request:more',
      'letter_of_third_party_detention:list',
      'letter_of_third_party_detention:more',
      'invoicing:list',
      'invoicing:more',
      'invoice_payment:list',
      'invoice_payment:more',
      'control_on_arrival:list',
      'control_on_arrival:more',
      'contract:list',
      'contract:more',
      'subcontract:list',
      'subcontract:more',
      'followup_of_contracts:view',
      'followup_of_commitments:view',

      'admin_finance:list',
      'admin_finance:more',

      'operating_expenses:list',
      'operating_expenses:more',
      'settlement_of_operating_expenses:list',
      'settlement_of_operating_expenses:more',
      'miscellaneous_expenses:list',
      'miscellaneous_expenses:more',
      'income_statement:view',
      'statement_of_expenses:view',

      'application_admin:list',
    ],
  },
  {
    id: 'fe931208-2e32-46ef-970a-7ac954b9f30c',
    libelle: 'admin',
    rules: [
      'dashboard_admin:view',

      'application_admin:add',
      'application_admin:list',
      'application_admin:more',
      'application_admin:list:action:delete',
      'application_admin:more:action:update',
      'application_admin:more:action:delete',
    ],
  },
  {
    id: '5b279c8e-c754-4153-a78d-24fa3d760fbf',
    libelle: 'accounting',
    rules: [
      'dashboard_acc:view',

      'operating_expenses:add',
      'operating_expenses:list',
      'operating_expenses:more',
      'operating_expenses:list:action:delete',
      'operating_expenses:more:action:update',
      'operating_expenses:more:action:delete',

      'miscellaneous_expenses:add',
      'miscellaneous_expenses:list',
      'miscellaneous_expenses:more',
      'miscellaneous_expenses:list:action:delete',
      'miscellaneous_expenses:more:action:update',
      'miscellaneous_expenses:more:action:delete',

      'settlement_of_operating_expenses:add',
      'settlement_of_operating_expenses:list',
      'settlement_of_operating_expenses:more',
      'settlement_of_operating_expenses:list:action:delete',
      'settlement_of_operating_expenses:more:action:update',
      'settlement_of_operating_expenses:more:action:delete',

      'income_statement:view',
      'statement_of_expenses:view',

      'admin_accounting:add',
      'admin_accounting:list',
      'admin_accounting:more',
      'admin_accounting:list:action:delete',
      'admin_accounting:more:action:update',
      'admin_accounting:more:action:delete',
    ],
  },
  {
    id: '6c109e86-94cc-4d99-b20a-5de0d6ea524c',
    libelle: 'financial',
    rules: [
      'dashboard_fin:view',

      'accounts:add',
      'accounts:list',
      'accounts:more',
      'accounts:list:action:delete',
      'accounts:more:action:update',
      'accounts:more:action:delete',

      'supplier_prefinancing:add',
      'supplier_prefinancing:list',
      'supplier_prefinancing:more',
      'supplier_prefinancing:list:action:delete',
      'supplier_prefinancing:more:action:update',
      'supplier_prefinancing:more:action:delete',

      'pledge_request:add',
      'pledge_request:list',
      'pledge_request:more',
      'pledge_request:list:action:delete',
      'pledge_request:more:action:update',
      'pledge_request:more:action:delete',

      'letter_of_third_party_detention:add',
      'letter_of_third_party_detention:list',
      'letter_of_third_party_detention:more',
      'letter_of_third_party_detention:list:action:delete',
      'letter_of_third_party_detention:more:action:update',
      'letter_of_third_party_detention:more:action:delete',

      'invoicing:add',
      'invoicing:list',
      'invoicing:more',
      'invoicing:list:action:delete',
      'invoicing:more:action:update',
      'invoicing:more:action:delete',

      'invoice_payment:add',
      'invoice_payment:list',
      'invoice_payment:more',
      'invoice_payment:list:action:delete',
      'invoice_payment:more:action:update',
      'invoice_payment:more:action:delete',

      'control_on_arrival:add',
      'control_on_arrival:list',
      'control_on_arrival:more',
      'control_on_arrival:list:action:delete',
      'control_on_arrival:more:action:update',
      'control_on_arrival:more:action:delete',

      'contract:add',
      'contract:list',
      'contract:more',
      'contract:list:action:delete',
      'contract:more:action:update',
      'contract:more:action:delete',

      'subcontract:add',
      'subcontract:list',
      'subcontract:more',
      'subcontract:list:action:delete',
      'subcontract:more:action:update',
      'subcontract:more:action:delete',

      'followup_of_contracts:view',
      'followup_of_commitments:view',

      'admin_finance:add',
      'admin_finance:list',
      'admin_finance:more',
      'admin_finance:list:action:delete',
      'admin_finance:more:action:update',
      'admin_finance:more:action:delete',
    ],
  },
  {
    id: '038e6a4e-09cb-49e8-96df-43321da52429',
    libelle: 'operator',
    rules: [
      'dashboard_ops:view',

      'unloading:add',
      'unloading:list',
      'unloading:more',
      'unloading:list:action:delete',
      'unloading:more:action:allow',
      'unloading:more:action:deny',
      'unloading:more:action:update',
      'unloading:more:action:delete',

      'storage:add',
      'storage:list',
      'storage:more',
      'storage:list:action:delete',
      'storage:more:action:allow',
      'storage:more:action:deny',
      'storage:more:action:update',
      'storage:more:action:delete',

      'validation:list',
      'validation:more',
      'validation:more:action:validate',

      'packing_plan:add',
      'packing_plan:list',
      'packing_plan:more',
      'packing_plan:list:action:delete',
      'packing_plan:more:action:allow',
      'packing_plan:more:action:deny',
      'packing_plan:more:action:update',
      'packing_plan:more:action:delete',

      'packing_execution:add',
      'packing_execution:list',
      'packing_execution:more',
      'packing_execution:list:action:delete',
      'packing_execution:more:action:allow',
      'packing_execution:more:action:deny',
      'packing_execution:more:action:update',
      'packing_execution:more:action:delete',

      'booking:add',
      'booking:list',
      'booking:more',
      'booking:list:action:delete',
      'booking:more:action:allow',
      'booking:more:action:deny',
      'booking:more:action:update',
      'booking:more:action:delete',

      'container:add',
      'container:list',
      'container:more',
      'container:list:action:delete',
      'container:more:action:allow',
      'container:more:action:deny',
      'container:more:action:update',
      'container:more:action:delete',

      'bill_of_lading:add',
      'bill_of_lading:list',
      'bill_of_lading:more',
      'bill_of_lading:list:action:delete',
      'bill_of_lading:more:action:allow',
      'bill_of_lading:more:action:deny',
      'bill_of_lading:more:action:update',
      'bill_of_lading:more:action:delete',

      'inventory:view',
      'exporter_report:view',
      'general_report:view',

      'admin_operation:add',
      'admin_operation:list',
      'admin_operation:more',
      'admin_operation:list:action:delete',
      'admin_operation:more:action:update',
      'admin_operation:more:action:delete',
    ],
  },
  {
    id: '821c83c6-d9e2-46ec-89b5-8fc1483a31f1',
    libelle: 'supervisor',
    rules: [
      'dashboard_sup:view',

      'unloading:add',
      'unloading:list',
      'unloading:more',
      'unloading:list:action:report',
      'unloading:list:action:delete',
      'unloading:more:action:update',
      'unloading:more:action:delete',

      'storage:add',
      'storage:list',
      'storage:more',
      'storage:list:action:report',
      'storage:list:action:delete',
      'storage:more:action:update',
      'storage:more:action:delete',

      'packing_execution:add',
      'packing_execution:list',
      'packing_execution:more',
      'packing_execution:list:action:delete',
      'packing_execution:more:action:update',
      'packing_execution:more:action:delete',

      'booking:add',
      'booking:list',
      'booking:more',
      'booking:list:action:delete',
      'booking:more:action:update',
      'booking:more:action:delete',

      'container:add',
      'container:list',
      'container:more',
      'container:list:action:delete',
      'container:more:action:update',
      'container:more:action:delete',

      'inventory:view',
    ],
  },
];
