export const configuration = () => {
  return {
    environment: process.env.NODE_ENV,
    port: process.env.APP_PORT,

    hostname: process.env.APP_HOSTNAME,
    appPrefix: process.env.APP_PREFIX,
    uploadDir: process.env.MULTER_DEST,
    fileUploadedSize: process.env.MAX_FILE_SIZE,
    imgUploadedSize: process.env.MAX_IMG_SIZE,
    throttleTTL: process.env.THROTTLE_TTL,
    throttleLimit: process.env.THROTTLE_LIMIT,

    dbHost: process.env.DB_HOST,
    dbUsername: process.env.DB_USERNAME,
    dbPassword: process.env.DB_PASSWORD,
    dbType: process.env.DB_TYPE,
    dbName: process.env.DB_NAME,
    dbPrefix: process.env.DB_PREFIX,
    dbPort: process.env.DB_PORT,
    dbSynchronize: process.env.DB_SYNCHRONIZE,
    dbLogger: process.env.DB_LOGGER,
    dbDropSchema: process.env.DB_DROP_SCHEMA,
    dbAutoLoadEntities: process.env.DB_AUTOLOAD_ENTITIES,
    dbCacheEnable: process.env.DB_CACHE_EANBLE,
    dbCacheType: process.env.DB_CACHE_TYPE,
    dbCacheDuration: process.env.DB_CACHE_DURATION,
    dbKeepConnectionAlive: process.env.DB_KEEP_CONNECTION_ALIVE,
    dbPoolSize: process.env.DB_POOL_SIZE,
    dbPoolConnexionTimeoutMillis: process.env.DB_POOL_CONNEXION_TIMEOUT_MILLIS,
    dbPoolIdleTimeoutMillis: process.env.DB_POOL_IDLE_TIMEOUT_MILLIS,
    dbPoolAllowExitOnIdle: process.env.DB_POOL_ALLOW_EXIT_ON_IDLE,

    rmqType: process.env.RMQ_TYPE,
    rmqHost: process.env.RMQ_HOST,
    rmqPort: process.env.RMQ_PORT,
    rmqUser: process.env.RMQ_USER,
    rmqPass: process.env.RMQ_PASS,
    rmqVHost: process.env.RMQ_VHOST,

    awsRegion: process.env.AWS_REGION,
    awsAccesKeyId: process.env.AWS_ACCESS_KEY_ID,
    awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    awsPublicBucketName: process.env.AWS_PUBLIC_BUCKET_NAME,

    swaggerTitle: process.env.SWAGGER_TITLE,
    swaggerDescription: process.env.SWAGGER_DESCRIPTION,
    swaggerVersion: process.env.SWAGGER_VERSION,
    swaggerTag: process.env.SWAGGER_TAG,
    swaggerUrl: process.env.SWAGGER_URL,

    passportStrategy: process.env.PASSPORT_STRATEGY,
    passportProperty: process.env.PASSPORT_PROPERTY,
    passportSession: process.env.PASSPORT_SESSION,

    auth0Domain: process.env.AUTH0_DOMAIN,
    auth0ClientId: process.env.AUTH0_CLIENT_ID,
    auth0ClientSecret: process.env.AUTH0_CLIENT_SECRET,
    auth0Audience: process.env.AUTH0_AUDIENCE,
    auth0GrantType: process.env.AUTH0_GRANT_TYPE,

    JwtSecretKey: process.env.JWT_SECRET,
    JwtPublicKey: process.env.JWT_PUBLIC_KEY,
    JwtPrivateKey: process.env.JWT_PRIVATE_KEY,
    JwtSecretOrKey: process.env.JWT_SECRET_OR_KEY,
    JwtSecretOrPrivateKey: process.env.JWT_SECRET_OR_PRIVATE_KEY,
    JwtAudience: process.env.JWT_AUDIENCE,
    JwtIssuer: process.env.JWT_ISSUER,
    JwtOptionExpiresIn: process.env.JWT_OPTION_EXPIRES_IN,
    JwtOptionAlgorithm: process.env.JWT_OPTION_ALGORITHM,
    JwtVerifOptionClockTolerence: process.env.JWT_VERIF_OPTION_CLOCK_TOLERANCE,
    JwtVerifOptionAlgorithm: process.env.JWT_VERIF_OPTION_ALGORITHM,
    JwtVerifOptionMaxAge: process.env.JWT_VERIF_OPTION_MAX_AGE,
  };
};
